import os

DBUS_NAME = "org.zbus.pompiliusd"
DBUS_PATH = "/org/zbus/pompiliusd"
DBUS_IFACE = "org.zbus.pompiliusd"

EXTENSION_DIR = os.path.dirname(os.path.abspath(__file__))

MAX_TIMEOUT_MS = 2**31 - 1  # Максимально возможный таймаут (около 24 дней)

R_MAP = {
    "alias": "Alias",
    "hdfs": "HDFS",
    "local": "Локальный диск",
    "protondrive": "Proton Drive",
    "storj": "Storj",
    "tardigrade": "Tardigrade",
    "cloudinary": "Cloudinary",
    "doi": "Digital Ocean Spaces",
    "fichier": "1Fichier",
    "filelu": "FileLu",
    "filescom": "Files.com",
    "ftp": "FTP",
    "http": "HTTP",
    "iclouddrive": "iCloud Drive",
    "imagekit": "ImageKit",
    "internetarchive": "Internet Archive",
    "koofr": "Koofr",
    "linkbox": "Linkbox",
    "mega": "Mega",
    "opendrive": "OpenDrive",
    "pixeldrain": "PixelDrain",
    "seafile": "Seafile",
    "sftp": "SFTP",
    "sia": "Sia",
    "smb": "SMB / CIFS",
    "ulozto": "Uloz.to",
    "uptobox": "Uptobox",
    "azurefiles": "Azure Files",
    "crypt": "Шифрованный диск",
    "gofile": "GoFile",
    "memory": "RAM диск",
    "netstorage": "Akamai NetStorage",
    "qingstor": "QingStor",
    "webdav": "WebDAV",
    "filefabric": "Storage Made Easy",
    "azureblob": "Azure Blob Storage",
    "quatrix": "Quatrix",
    "b2": "Backblaze B2",
    "cache": "Кеш",
    "chunker": "Chunker",
    "combine": "Combine",
    "hasher": "Hasher",
    "oracleobjectstorage": "Oracle Object Storage",
    "s3": "Amazon S3",
    "sugarsync": "SugarSync",
    "swift": "OpenStack Swift",
    "union": "Union",
    "compress": "Сжатие",
    "dropbox": "Dropbox",
    "google photos": "Google Photos",
    "hidrive": "HiDrive",
    "jottacloud": "Jottacloud",
    "mailru": "Облако@Mail.ru",
    "onedrive": "OneDrive",
    "pcloud": "pCloud",
    "pikpak": "PikPak",
    "premiumizeme": "Premiumize.me",
    "putio": "Put.io",
    "sharefile": "Citrix ShareFile",
    "yandex": "Яндекс.Диск",
    "zoho": "Zoho WorkDrive",
    "box": "Box",
    "archive": "Archive",
    "drive": "Google Drive",
    "google cloud storage": "Google Cloud Storage",
}

LOGO_MAP = {
    "drive": "google-drive-logo.png",
    "yandex": "yandex-disk-logo.png",
    "iclouddrive": "i-cloud-logo.svg",
    "mailru": "mail-ru-logo.svg",
    "dropbox": "dropbox-logo.svg",
    "onedrive": "onedrive-logo.webp",
    "mega": "mega-logo.svg",
    "pcloud": "pcloud-logo.svg",
    "box": "box-logo.svg",
    "s3": "amazon.png",
    "imagekit": "imagekit-logo.png",
    "swift": "openstack-logo.svg",
    "azurefiles": "azure-logo.svg",
    "azureblob": "azure-logo.svg",
    "b2": "backblaze-logo.svg",
    "protondrive": "proton-logo.svg",
    "google cloud storage": "google-cloud-storage.svg",
    "google photos": "google-photos-logo.png",
    "zoho": "zoho-logo.svg",
    "koofr": "koofr-logo.svg",
    "putio": "put-io-logo.svg",
    "seafile": "seafile-logo.png",
    "storj": "storj-logo.svg",
    "selectel": "selectel.svg",
    "sftp": "openssh-logo.png",
    "webdav": "webdav-logo.jpg",
    "smb": "samba-logo.svg",
}

PROTOCOL_ICONS = {
    "ftp": "network-server-symbolic",
    "sftp": "network-server-symbolic",
    "webdav": "webdav-logo.png",
    "smb": "network-workgroup-symbolic",
    "http": "text-html-symbolic",
    "local": "drive-harddisk-symbolic",
    "crypt": "channel-insecure-symbolic",
    "cache": "media-flash-symbolic",
    "compress": "package-x-generic-symbolic",
}
